package com.zipoapps.domain.exceptions

class ConnectionErrorException() : Throwable()
